### ISSUE TITLE
SegWit: coins sent to witness address doesn't appear any more and not mined

### ISSUE THREAD

**Issue by wqking** [phoreproject/Phore#31] opened 2018-04-24 02:56 UTC
Network is regtest. The binary is I compiled from SegWit branch.
I send some coins to witness address, after mining a new block, the new block doesn't contain that transaction.

Reproduce:

SegWit: coins sent to witness address doesn't appear any more and not mined

Network is regtest.
I send some coins to witness address, after mining a new block, the new block doesn't contain that transaction.

Reproduce:

1. Run the daemon
```phored -regtest```

2. Run the RPCs, comment is in //

// set the mock time to enable SegWit
```phore-cli -regtest setmocktime 4071908800```

// get a new normal address
```phore-cli -regtest getnewaddress```
yHrW14YkawSTPBGY5hKuTS11VMMrkabCAF

// generate a new witness address
```phore-cli -regtest addwitnessaddress yHrW14YkawSTPBGY5hKuTS11VMMrkabCAF```
8uBqkmxYhhLWjf1KvLd5dDKBMQDkFTUXds

// mine 150 blocks.
```phore-cli -regtest setgenerate true 150```

// send some amount to witness address
```phore-cli -regtest sendtoaddress 8uBqkmxYhhLWjf1KvLd5dDKBMQDkFTUXds 17870000```
b36267fae4a46f353336cd68db4a9e568ea77f6ecfbedc59967d4ea0d8d75757

// mine a new block
```phore-cli -regtest setgenerate true 1```
2b7ed3b4efdd6b06fb3eb545c3f5b786953a153c8de2967d21028c94e1e69bd2

// check the new mined block. It only contains one transaction which is the coinbase. It should contain two transactions and one transaction is the one sent above.
```phore-cli -regtest getblock 2b7ed3b4efdd6b06fb3eb545c3f5b786953a153c8de2967d21028c94e1e69bd2```

Note, seems this issue is not specified to SegWit. Sending to a normal address still have this issues.
Note, I tested on Bitcoin regtest, it shows two transactions in the last "getblock" step, which is correct.

**Comment by meyer9** [comment] 2018-04-24 03:39
Could not reproduce on regtest. Can you confirm you are on the latest commit?

**Comment by meyer9** [comment] 2018-04-24 03:48
Was able to reproduce on testnet chain

**Comment by meyer9** [comment] 2018-04-24 03:52
Pushed a fix. I had fixed this bug earlier. Re-open if you're still having issues

**Closed as completed by meyer9** 2018-04-24 03:52 UTC
Labels: bug
